Run error job before success job always

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,13 +1,13 @@
 name: CI
 on: [push]
 jobs:
-  success:
+  error:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Fake Successful Deploy
+      - name: Fake Errored Deploy
         id: deploy
-        run: echo "::set-output name=preview_url::https://shopify.dev/hydrogen"
+        run: echo "ERROR!!" 1>&2
       - name: Create GitHub Deployment
         id: github-deployment-action
         uses: ./
@@ -17,13 +17,15 @@ jobs:
           preview_url: ${{ steps.deploy.outputs.preview_url }}
           description: ${{ github.event.head_commit.message }}
 
-  error:
+  success:
+    if: always()
+    needs: [error]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Fake Errored Deploy
+      - name: Fake Successful Deploy
         id: deploy
-        run: echo "ERROR!!" 1>&2
+        run: echo "::set-output name=preview_url::https://shopify.dev/hydrogen"
       - name: Create GitHub Deployment
         id: github-deployment-action
         uses: ./
