Add pending status

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,6 +1,40 @@
 name: CI
 on: [push]
 jobs:
+  error:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Fake Errored Deploy
+        id: deploy
+        run: echo "ERROR!!" 1>&2
+      - name: Create GitHub Deployment
+        id: github-deployment-action
+        uses: ./
+        with:
+          token: ${{ github.token }}
+          environment: 'preview'
+          preview_url: ${{ steps.deploy.outputs.preview_url }}
+          description: ${{ github.event.head_commit.message }}
+
+  pending:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Fake Long Deploy
+        id: deploy
+        run: |
+          sleep 60
+          echo "::set-output name=preview_url::https://shopify.dev/hydrogen"
+      - name: Create GitHub Deployment
+        id: github-deployment-action
+        uses: ./
+        with:
+          token: ${{ github.token }}
+          environment: 'preview'
+          preview_url: ${{ steps.deploy.outputs.preview_url }}
+          description: ${{ github.event.head_commit.message }}
+
   success:
     runs-on: ubuntu-latest
     steps:
@@ -17,18 +51,3 @@ jobs:
           preview_url: ${{ steps.deploy.outputs.preview_url }}
           description: ${{ github.event.head_commit.message }}
 
-  error:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Fake Errored Deploy
-        id: deploy
-        run: echo "ERROR!!" 1>&2
-      - name: Create GitHub Deployment
-        id: github-deployment-action
-        uses: ./
-        with:
-          token: ${{ github.token }}
-          environment: 'preview'
-          preview_url: ${{ steps.deploy.outputs.preview_url }}
-          description: ${{ github.event.head_commit.message }}
